-- ==================================================
-- 生産管理システム（PMS）デモ用スキーマ
-- H2 Database 互換（chapter23.md 準拠）
-- ==================================================

-- --------------------------------------------------
-- 単位マスタ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "単位マスタ" (
    "単位コード" VARCHAR(10) PRIMARY KEY,
    "単位記号" VARCHAR(10) NOT NULL,
    "単位名" VARCHAR(50) NOT NULL,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- --------------------------------------------------
-- 品目マスタ（世代管理対応）
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "品目マスタ" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "品目コード" VARCHAR(20) NOT NULL,
    "適用開始日" DATE NOT NULL,
    "適用停止日" DATE,
    "品名" VARCHAR(100) NOT NULL,
    "品目区分" VARCHAR(20) NOT NULL,
    "単位コード" VARCHAR(10),
    "リードタイム" INTEGER DEFAULT 0,
    "安全リードタイム" INTEGER DEFAULT 0,
    "安全在庫数" DECIMAL(15, 2) DEFAULT 0,
    "歩留率" DECIMAL(5, 2) DEFAULT 100,
    "最小ロット数" DECIMAL(15, 2) DEFAULT 1,
    "刻みロット数" DECIMAL(15, 2) DEFAULT 1,
    "最大ロット数" DECIMAL(15, 2),
    "有効期間" INTEGER,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_品目マスタ UNIQUE("品目コード", "適用開始日")
);

CREATE INDEX IF NOT EXISTS idx_品目マスタ_品目コード ON "品目マスタ"("品目コード");
CREATE INDEX IF NOT EXISTS idx_品目マスタ_品目区分 ON "品目マスタ"("品目区分");

-- --------------------------------------------------
-- 部品構成表（BOM）
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "部品構成表" (
    "親品目コード" VARCHAR(20) NOT NULL,
    "子品目コード" VARCHAR(20) NOT NULL,
    "適用開始日" DATE NOT NULL,
    "適用停止日" DATE,
    "基準数量" DECIMAL(15, 2) NOT NULL DEFAULT 1,
    "必要数量" DECIMAL(15, 2) NOT NULL,
    "不良率" DECIMAL(5, 2) DEFAULT 0,
    "工順" INTEGER,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("親品目コード", "子品目コード", "適用開始日")
);

CREATE INDEX IF NOT EXISTS idx_bom_親品目コード ON "部品構成表"("親品目コード");
CREATE INDEX IF NOT EXISTS idx_bom_子品目コード ON "部品構成表"("子品目コード");

-- --------------------------------------------------
-- カレンダマスタ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "カレンダマスタ" (
    "カレンダコード" VARCHAR(20) NOT NULL,
    "日付" DATE NOT NULL,
    "日付区分" VARCHAR(20) NOT NULL DEFAULT '稼働日',
    "稼働時間" DECIMAL(5, 2),
    "備考" VARCHAR(200),
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("カレンダコード", "日付")
);

-- --------------------------------------------------
-- 場所マスタ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "場所マスタ" (
    "場所コード" VARCHAR(20) PRIMARY KEY,
    "場所名" VARCHAR(100) NOT NULL,
    "場所区分" VARCHAR(20) NOT NULL,
    "親場所コード" VARCHAR(20),
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_場所マスタ_場所区分 ON "場所マスタ"("場所区分");

-- 自己参照外部キーは後で追加（H2の制約対応）
ALTER TABLE "場所マスタ" ADD CONSTRAINT IF NOT EXISTS fk_場所マスタ_親
    FOREIGN KEY ("親場所コード") REFERENCES "場所マスタ"("場所コード");

-- --------------------------------------------------
-- 取引先マスタ（世代管理対応）
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "取引先マスタ" (
    "取引先コード" VARCHAR(20) NOT NULL,
    "適用開始日" DATE NOT NULL,
    "適用停止日" DATE,
    "取引先名" VARCHAR(100) NOT NULL,
    "取引先カナ" VARCHAR(100),
    "取引先区分" VARCHAR(20) NOT NULL,
    "郵便番号" VARCHAR(10),
    "住所" VARCHAR(200),
    "電話番号" VARCHAR(20),
    "FAX番号" VARCHAR(20),
    "担当者名" VARCHAR(50),
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("取引先コード", "適用開始日")
);

CREATE INDEX IF NOT EXISTS idx_取引先マスタ_取引先区分 ON "取引先マスタ"("取引先区分");

-- --------------------------------------------------
-- 部門マスタ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "部門マスタ" (
    "部門コード" VARCHAR(10) PRIMARY KEY,
    "部門名" VARCHAR(100) NOT NULL,
    "部門パス" VARCHAR(500),
    "最下層区分" BOOLEAN DEFAULT FALSE,
    "有効開始日" DATE NOT NULL,
    "有効終了日" DATE,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- --------------------------------------------------
-- 担当者マスタ（世代管理対応）
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "担当者マスタ" (
    "担当者コード" VARCHAR(10) NOT NULL,
    "適用開始日" DATE NOT NULL,
    "適用停止日" DATE,
    "担当者名" VARCHAR(100) NOT NULL,
    "部門コード" VARCHAR(10),
    "メールアドレス" VARCHAR(255),
    "電話番号" VARCHAR(20),
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("担当者コード", "適用開始日")
);

-- --------------------------------------------------
-- 工程マスタ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "工程マスタ" (
    "工程コード" VARCHAR(10) PRIMARY KEY,
    "工程名" VARCHAR(100) NOT NULL,
    "工程区分" VARCHAR(20),
    "場所コード" VARCHAR(20),
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- --------------------------------------------------
-- 工程表
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "工程表" (
    "品目コード" VARCHAR(20) NOT NULL,
    "工順" INTEGER NOT NULL,
    "工程コード" VARCHAR(10) NOT NULL,
    "標準作業時間" DECIMAL(10, 2),
    "段取時間" DECIMAL(10, 2),
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("品目コード", "工順")
);

CREATE INDEX IF NOT EXISTS idx_工程表_品目コード ON "工程表"("品目コード");

-- --------------------------------------------------
-- 単価マスタ（世代管理対応）
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "単価マスタ" (
    "品目コード" VARCHAR(20) NOT NULL,
    "取引先コード" VARCHAR(20) NOT NULL,
    "適用開始日" DATE NOT NULL,
    "適用停止日" DATE,
    "単価" DECIMAL(15, 2) NOT NULL,
    "通貨コード" VARCHAR(3) DEFAULT 'JPY',
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("品目コード", "取引先コード", "適用開始日")
);

CREATE INDEX IF NOT EXISTS idx_単価マスタ_品目コード ON "単価マスタ"("品目コード");
CREATE INDEX IF NOT EXISTS idx_単価マスタ_取引先コード ON "単価マスタ"("取引先コード");

-- --------------------------------------------------
-- 欠点マスタ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "欠点マスタ" (
    "欠点コード" VARCHAR(10) PRIMARY KEY,
    "欠点名" VARCHAR(100) NOT NULL,
    "欠点区分" VARCHAR(20),
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==================================================
-- 生産計画テーブル（chapter24.md 準拠）
-- ==================================================

-- --------------------------------------------------
-- 基準生産計画
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "基準生産計画" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MPS番号" VARCHAR(20) UNIQUE NOT NULL,
    "計画日" DATE NOT NULL,
    "品目コード" VARCHAR(20) NOT NULL,
    "計画数量" DECIMAL(15, 2) NOT NULL,
    "納期" DATE NOT NULL,
    "ステータス" VARCHAR(20) DEFAULT '草案' NOT NULL,
    "場所コード" VARCHAR(20),
    "備考" TEXT,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "作成者" VARCHAR(50),
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新者" VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_基準生産計画_品目コード ON "基準生産計画"("品目コード");
CREATE INDEX IF NOT EXISTS idx_基準生産計画_納期 ON "基準生産計画"("納期");
CREATE INDEX IF NOT EXISTS idx_基準生産計画_ステータス ON "基準生産計画"("ステータス");

-- --------------------------------------------------
-- オーダ情報（購買・製造共通）
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "オーダ情報" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "オーダNO" VARCHAR(20) UNIQUE NOT NULL,
    "オーダ種別" VARCHAR(20) NOT NULL,
    "品目コード" VARCHAR(20) NOT NULL,
    "着手予定日" DATE NOT NULL,
    "納期" DATE NOT NULL,
    "有効期限" DATE,
    "計画数量" DECIMAL(15, 2) NOT NULL,
    "場所コード" VARCHAR(20) NOT NULL,
    "ステータス" VARCHAR(20) DEFAULT '草案' NOT NULL,
    "MPS_ID" INTEGER,
    "親オーダID" INTEGER,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "作成者" VARCHAR(50),
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新者" VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_オーダ情報_品目コード ON "オーダ情報"("品目コード");
CREATE INDEX IF NOT EXISTS idx_オーダ情報_納期 ON "オーダ情報"("納期");
CREATE INDEX IF NOT EXISTS idx_オーダ情報_MPS_ID ON "オーダ情報"("MPS_ID");
CREATE INDEX IF NOT EXISTS idx_オーダ情報_オーダ種別 ON "オーダ情報"("オーダ種別");

-- 外部キー（H2の制約対応）
ALTER TABLE "オーダ情報" ADD CONSTRAINT IF NOT EXISTS fk_オーダ情報_MPS
    FOREIGN KEY ("MPS_ID") REFERENCES "基準生産計画"("ID");
ALTER TABLE "オーダ情報" ADD CONSTRAINT IF NOT EXISTS fk_オーダ情報_親オーダ
    FOREIGN KEY ("親オーダID") REFERENCES "オーダ情報"("ID");

-- --------------------------------------------------
-- 所要情報
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "所要情報" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "所要NO" VARCHAR(20) UNIQUE NOT NULL,
    "オーダID" INTEGER NOT NULL,
    "品目コード" VARCHAR(20) NOT NULL,
    "納期" DATE NOT NULL,
    "必要数量" DECIMAL(15, 2) NOT NULL,
    "引当済数量" DECIMAL(15, 2) DEFAULT 0 NOT NULL,
    "不足数量" DECIMAL(15, 2) DEFAULT 0 NOT NULL,
    "場所コード" VARCHAR(20) NOT NULL,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_所要情報_オーダID ON "所要情報"("オーダID");
CREATE INDEX IF NOT EXISTS idx_所要情報_品目コード ON "所要情報"("品目コード");

-- 外部キー（H2の制約対応）
ALTER TABLE "所要情報" ADD CONSTRAINT IF NOT EXISTS fk_所要情報_オーダ
    FOREIGN KEY ("オーダID") REFERENCES "オーダ情報"("ID");

-- --------------------------------------------------
-- 引当情報
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "引当情報" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "所要ID" INTEGER NOT NULL,
    "引当区分" VARCHAR(20) NOT NULL,
    "オーダID" INTEGER,
    "引当日" DATE NOT NULL,
    "引当数量" DECIMAL(15, 2) NOT NULL,
    "場所コード" VARCHAR(20) NOT NULL,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_引当情報_所要ID ON "引当情報"("所要ID");

-- 外部キー（H2の制約対応）
ALTER TABLE "引当情報" ADD CONSTRAINT IF NOT EXISTS fk_引当情報_所要
    FOREIGN KEY ("所要ID") REFERENCES "所要情報"("ID");
ALTER TABLE "引当情報" ADD CONSTRAINT IF NOT EXISTS fk_引当情報_オーダ
    FOREIGN KEY ("オーダID") REFERENCES "オーダ情報"("ID");

-- ==================================================
-- 購買管理テーブル（chapter25.md 準拠）
-- ==================================================

-- --------------------------------------------------
-- 発注データ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "発注データ" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "発注番号" VARCHAR(20) UNIQUE NOT NULL,
    "発注日" DATE NOT NULL,
    "取引先コード" VARCHAR(20) NOT NULL,
    "発注担当者コード" VARCHAR(20),
    "発注部門コード" VARCHAR(20),
    "ステータス" VARCHAR(20) DEFAULT '作成中' NOT NULL,
    "備考" TEXT,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "作成者" VARCHAR(50),
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新者" VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_発注データ_取引先コード ON "発注データ"("取引先コード");
CREATE INDEX IF NOT EXISTS idx_発注データ_発注日 ON "発注データ"("発注日");

-- --------------------------------------------------
-- 発注明細データ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "発注明細データ" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "発注番号" VARCHAR(20) NOT NULL,
    "発注行番号" INTEGER NOT NULL,
    "オーダNO" VARCHAR(20),
    "納入場所コード" VARCHAR(20),
    "品目コード" VARCHAR(20) NOT NULL,
    "諸口品目区分" BOOLEAN DEFAULT FALSE NOT NULL,
    "受入予定日" DATE NOT NULL,
    "回答納期" DATE,
    "発注単価" DECIMAL(15, 2) NOT NULL,
    "発注数量" DECIMAL(15, 2) NOT NULL,
    "入荷済数量" DECIMAL(15, 2) DEFAULT 0 NOT NULL,
    "検査済数量" DECIMAL(15, 2) DEFAULT 0 NOT NULL,
    "検収済数量" DECIMAL(15, 2) DEFAULT 0 NOT NULL,
    "発注金額" DECIMAL(15, 2) NOT NULL,
    "消費税金額" DECIMAL(15, 2) DEFAULT 0 NOT NULL,
    "完了フラグ" BOOLEAN DEFAULT FALSE NOT NULL,
    "明細備考" TEXT,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "作成者" VARCHAR(50),
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新者" VARCHAR(50),
    CONSTRAINT uk_発注明細 UNIQUE ("発注番号", "発注行番号")
);

CREATE INDEX IF NOT EXISTS idx_発注明細_発注番号 ON "発注明細データ"("発注番号");
CREATE INDEX IF NOT EXISTS idx_発注明細_品目コード ON "発注明細データ"("品目コード");

-- 外部キー（H2の制約対応）
ALTER TABLE "発注明細データ" ADD CONSTRAINT IF NOT EXISTS fk_発注明細_発注
    FOREIGN KEY ("発注番号") REFERENCES "発注データ"("発注番号");

-- --------------------------------------------------
-- 諸口品目情報
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "諸口品目情報" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "発注番号" VARCHAR(20) NOT NULL,
    "発注行番号" INTEGER NOT NULL,
    "品目コード" VARCHAR(20) NOT NULL,
    "品名" VARCHAR(100) NOT NULL,
    "規格" VARCHAR(100),
    "図番メーカー" VARCHAR(100),
    "版数" VARCHAR(20),
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_諸口品目 UNIQUE ("発注番号", "発注行番号", "品目コード")
);

-- --------------------------------------------------
-- 入荷受入データ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "入荷受入データ" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "入荷番号" VARCHAR(20) UNIQUE NOT NULL,
    "発注番号" VARCHAR(20) NOT NULL,
    "発注行番号" INTEGER NOT NULL,
    "入荷日" DATE NOT NULL,
    "入荷担当者コード" VARCHAR(20),
    "入荷受入区分" VARCHAR(20) DEFAULT '通常入荷' NOT NULL,
    "品目コード" VARCHAR(20) NOT NULL,
    "諸口品目区分" BOOLEAN DEFAULT FALSE NOT NULL,
    "入荷数量" DECIMAL(15, 2) NOT NULL,
    "入荷備考" TEXT,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "作成者" VARCHAR(50),
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新者" VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_入荷受入_発注番号 ON "入荷受入データ"("発注番号", "発注行番号");
CREATE INDEX IF NOT EXISTS idx_入荷受入_入荷日 ON "入荷受入データ"("入荷日");

-- 外部キー（H2の制約対応）
ALTER TABLE "入荷受入データ" ADD CONSTRAINT IF NOT EXISTS fk_入荷受入_発注明細
    FOREIGN KEY ("発注番号", "発注行番号") REFERENCES "発注明細データ"("発注番号", "発注行番号");

-- --------------------------------------------------
-- 受入検査データ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "受入検査データ" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "受入検査番号" VARCHAR(20) UNIQUE NOT NULL,
    "入荷番号" VARCHAR(20) NOT NULL,
    "発注番号" VARCHAR(20) NOT NULL,
    "発注行番号" INTEGER NOT NULL,
    "受入検査日" DATE NOT NULL,
    "受入検査担当者コード" VARCHAR(20),
    "品目コード" VARCHAR(20) NOT NULL,
    "諸口品目区分" BOOLEAN DEFAULT FALSE NOT NULL,
    "良品数" DECIMAL(15, 2) NOT NULL,
    "不良品数" DECIMAL(15, 2) DEFAULT 0 NOT NULL,
    "受入検査備考" TEXT,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "作成者" VARCHAR(50),
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新者" VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_受入検査_入荷番号 ON "受入検査データ"("入荷番号");

-- 外部キー（H2の制約対応）
ALTER TABLE "受入検査データ" ADD CONSTRAINT IF NOT EXISTS fk_受入検査_入荷
    FOREIGN KEY ("入荷番号") REFERENCES "入荷受入データ"("入荷番号");

-- --------------------------------------------------
-- 検収データ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "検収データ" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "検収番号" VARCHAR(20) UNIQUE NOT NULL,
    "受入検査番号" VARCHAR(20) NOT NULL,
    "発注番号" VARCHAR(20) NOT NULL,
    "発注行番号" INTEGER NOT NULL,
    "検収日" DATE NOT NULL,
    "検収担当者コード" VARCHAR(20),
    "取引先コード" VARCHAR(20) NOT NULL,
    "品目コード" VARCHAR(20) NOT NULL,
    "諸口品目区分" BOOLEAN DEFAULT FALSE NOT NULL,
    "検収数" DECIMAL(15, 2) NOT NULL,
    "検収単価" DECIMAL(15, 2) NOT NULL,
    "検収金額" DECIMAL(15, 2) NOT NULL,
    "検収消費税額" DECIMAL(15, 2) DEFAULT 0 NOT NULL,
    "検収備考" TEXT,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "作成者" VARCHAR(50),
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新者" VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_検収_受入検査番号 ON "検収データ"("受入検査番号");
CREATE INDEX IF NOT EXISTS idx_検収_発注番号 ON "検収データ"("発注番号", "発注行番号");

-- 外部キー（H2の制約対応）
ALTER TABLE "検収データ" ADD CONSTRAINT IF NOT EXISTS fk_検収_受入検査
    FOREIGN KEY ("受入検査番号") REFERENCES "受入検査データ"("受入検査番号");
ALTER TABLE "検収データ" ADD CONSTRAINT IF NOT EXISTS fk_検収_発注明細
    FOREIGN KEY ("発注番号", "発注行番号") REFERENCES "発注明細データ"("発注番号", "発注行番号");

-- ==================================================
-- 外注委託管理テーブル（chapter26.md 準拠）
-- ==================================================

-- --------------------------------------------------
-- 支給データ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "支給データ" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "支給番号" VARCHAR(20) UNIQUE NOT NULL,
    "発注番号" VARCHAR(20) NOT NULL,
    "発注行番号" INTEGER NOT NULL,
    "取引先コード" VARCHAR(20) NOT NULL,
    "支給日" DATE NOT NULL,
    "支給担当者コード" VARCHAR(20) NOT NULL,
    "支給区分" VARCHAR(20) DEFAULT '無償支給' NOT NULL,
    "備考" TEXT,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "作成者" VARCHAR(50),
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新者" VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_支給データ_発注番号 ON "支給データ"("発注番号", "発注行番号");
CREATE INDEX IF NOT EXISTS idx_支給データ_取引先コード ON "支給データ"("取引先コード");
CREATE INDEX IF NOT EXISTS idx_支給データ_支給日 ON "支給データ"("支給日");

-- 外部キー（H2の制約対応）
ALTER TABLE "支給データ" ADD CONSTRAINT IF NOT EXISTS fk_支給データ_発注明細
    FOREIGN KEY ("発注番号", "発注行番号") REFERENCES "発注明細データ"("発注番号", "発注行番号");

-- --------------------------------------------------
-- 支給明細データ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "支給明細データ" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "支給番号" VARCHAR(20) NOT NULL,
    "支給行番号" INTEGER NOT NULL,
    "品目コード" VARCHAR(20) NOT NULL,
    "支給数" DECIMAL(15, 2) NOT NULL,
    "支給単価" DECIMAL(15, 2) NOT NULL,
    "支給金額" DECIMAL(15, 2) NOT NULL,
    "備考" TEXT,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "作成者" VARCHAR(50),
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新者" VARCHAR(50),
    CONSTRAINT uk_支給明細 UNIQUE ("支給番号", "支給行番号")
);

CREATE INDEX IF NOT EXISTS idx_支給明細_支給番号 ON "支給明細データ"("支給番号");
CREATE INDEX IF NOT EXISTS idx_支給明細_品目コード ON "支給明細データ"("品目コード");

-- 外部キー（H2の制約対応）
ALTER TABLE "支給明細データ" ADD CONSTRAINT IF NOT EXISTS fk_支給明細_支給
    FOREIGN KEY ("支給番号") REFERENCES "支給データ"("支給番号");

-- --------------------------------------------------
-- 消費データ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "消費データ" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "消費番号" VARCHAR(20) UNIQUE NOT NULL,
    "入荷番号" VARCHAR(20) NOT NULL,
    "消費日" DATE NOT NULL,
    "取引先コード" VARCHAR(20) NOT NULL,
    "備考" TEXT,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "作成者" VARCHAR(50),
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新者" VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_消費データ_入荷番号 ON "消費データ"("入荷番号");
CREATE INDEX IF NOT EXISTS idx_消費データ_取引先コード ON "消費データ"("取引先コード");
CREATE INDEX IF NOT EXISTS idx_消費データ_消費日 ON "消費データ"("消費日");

-- 外部キー（H2の制約対応）
ALTER TABLE "消費データ" ADD CONSTRAINT IF NOT EXISTS fk_消費データ_入荷
    FOREIGN KEY ("入荷番号") REFERENCES "入荷受入データ"("入荷番号");

-- --------------------------------------------------
-- 消費明細データ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "消費明細データ" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "消費番号" VARCHAR(20) NOT NULL,
    "消費行番号" INTEGER NOT NULL,
    "品目コード" VARCHAR(20) NOT NULL,
    "消費数量" DECIMAL(15, 2) NOT NULL,
    "備考" TEXT,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "作成者" VARCHAR(50),
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新者" VARCHAR(50),
    CONSTRAINT uk_消費明細 UNIQUE ("消費番号", "消費行番号")
);

CREATE INDEX IF NOT EXISTS idx_消費明細_消費番号 ON "消費明細データ"("消費番号");
CREATE INDEX IF NOT EXISTS idx_消費明細_品目コード ON "消費明細データ"("品目コード");

-- 外部キー（H2の制約対応）
ALTER TABLE "消費明細データ" ADD CONSTRAINT IF NOT EXISTS fk_消費明細_消費
    FOREIGN KEY ("消費番号") REFERENCES "消費データ"("消費番号");

-- ==================================================
-- 工程管理テーブル（chapter27.md 準拠）
-- ==================================================

-- --------------------------------------------------
-- 作業指示データ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "作業指示データ" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "作業指示番号" VARCHAR(20) UNIQUE NOT NULL,
    "オーダ番号" VARCHAR(20) NOT NULL,
    "作業指示日" DATE NOT NULL,
    "品目コード" VARCHAR(20) NOT NULL,
    "作業指示数" DECIMAL(15, 2) NOT NULL,
    "場所コード" VARCHAR(20) NOT NULL,
    "開始予定日" DATE NOT NULL,
    "完成予定日" DATE NOT NULL,
    "実績開始日" DATE,
    "実績完了日" DATE,
    "完成済数" DECIMAL(15, 2) DEFAULT 0 NOT NULL,
    "総良品数" DECIMAL(15, 2) DEFAULT 0 NOT NULL,
    "総不良品数" DECIMAL(15, 2) DEFAULT 0 NOT NULL,
    "ステータス" VARCHAR(20) DEFAULT '未着手' NOT NULL,
    "完了フラグ" BOOLEAN DEFAULT FALSE NOT NULL,
    "備考" TEXT,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "作成者" VARCHAR(50),
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新者" VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_作業指示_オーダ番号 ON "作業指示データ"("オーダ番号");
CREATE INDEX IF NOT EXISTS idx_作業指示_品目コード ON "作業指示データ"("品目コード");
CREATE INDEX IF NOT EXISTS idx_作業指示_ステータス ON "作業指示データ"("ステータス");
CREATE INDEX IF NOT EXISTS idx_作業指示_作業指示日 ON "作業指示データ"("作業指示日");

-- 外部キー（H2の制約対応）
ALTER TABLE "作業指示データ" ADD CONSTRAINT IF NOT EXISTS fk_作業指示_オーダ
    FOREIGN KEY ("オーダ番号") REFERENCES "オーダ情報"("オーダNO");
ALTER TABLE "作業指示データ" ADD CONSTRAINT IF NOT EXISTS fk_作業指示_場所
    FOREIGN KEY ("場所コード") REFERENCES "場所マスタ"("場所コード");

-- --------------------------------------------------
-- 作業指示明細データ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "作業指示明細データ" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "作業指示番号" VARCHAR(20) NOT NULL,
    "工順" INTEGER NOT NULL,
    "工程コード" VARCHAR(10) NOT NULL,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "作成者" VARCHAR(50),
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新者" VARCHAR(50),
    CONSTRAINT uk_作業指示明細 UNIQUE ("作業指示番号", "工順")
);

CREATE INDEX IF NOT EXISTS idx_作業指示明細_作業指示番号 ON "作業指示明細データ"("作業指示番号");
CREATE INDEX IF NOT EXISTS idx_作業指示明細_工程コード ON "作業指示明細データ"("工程コード");

-- 外部キー（H2の制約対応）
ALTER TABLE "作業指示明細データ" ADD CONSTRAINT IF NOT EXISTS fk_作業指示明細_作業指示
    FOREIGN KEY ("作業指示番号") REFERENCES "作業指示データ"("作業指示番号");
ALTER TABLE "作業指示明細データ" ADD CONSTRAINT IF NOT EXISTS fk_作業指示明細_工程
    FOREIGN KEY ("工程コード") REFERENCES "工程マスタ"("工程コード");

-- --------------------------------------------------
-- 完成実績データ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "完成実績データ" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "完成実績番号" VARCHAR(20) UNIQUE NOT NULL,
    "作業指示番号" VARCHAR(20) NOT NULL,
    "品目コード" VARCHAR(20) NOT NULL,
    "完成日" DATE NOT NULL,
    "完成数量" DECIMAL(15, 2) NOT NULL,
    "良品数" DECIMAL(15, 2) NOT NULL,
    "不良品数" DECIMAL(15, 2) NOT NULL,
    "備考" TEXT,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "作成者" VARCHAR(50),
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新者" VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_完成実績_作業指示番号 ON "完成実績データ"("作業指示番号");
CREATE INDEX IF NOT EXISTS idx_完成実績_品目コード ON "完成実績データ"("品目コード");
CREATE INDEX IF NOT EXISTS idx_完成実績_完成日 ON "完成実績データ"("完成日");

-- 外部キー（H2の制約対応）
ALTER TABLE "完成実績データ" ADD CONSTRAINT IF NOT EXISTS fk_完成実績_作業指示
    FOREIGN KEY ("作業指示番号") REFERENCES "作業指示データ"("作業指示番号");

-- --------------------------------------------------
-- 完成検査結果データ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "完成検査結果データ" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "完成実績番号" VARCHAR(20) NOT NULL,
    "欠点コード" VARCHAR(10) NOT NULL,
    "数量" DECIMAL(15, 2) NOT NULL,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "作成者" VARCHAR(50),
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新者" VARCHAR(50),
    CONSTRAINT uk_完成検査結果 UNIQUE ("完成実績番号", "欠点コード")
);

CREATE INDEX IF NOT EXISTS idx_完成検査結果_完成実績番号 ON "完成検査結果データ"("完成実績番号");

-- 外部キー（H2の制約対応）
ALTER TABLE "完成検査結果データ" ADD CONSTRAINT IF NOT EXISTS fk_完成検査結果_完成実績
    FOREIGN KEY ("完成実績番号") REFERENCES "完成実績データ"("完成実績番号");
ALTER TABLE "完成検査結果データ" ADD CONSTRAINT IF NOT EXISTS fk_完成検査結果_欠点
    FOREIGN KEY ("欠点コード") REFERENCES "欠点マスタ"("欠点コード");

-- --------------------------------------------------
-- 工数実績データ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "工数実績データ" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "工数実績番号" VARCHAR(20) UNIQUE NOT NULL,
    "作業指示番号" VARCHAR(20) NOT NULL,
    "品目コード" VARCHAR(20) NOT NULL,
    "工順" INTEGER NOT NULL,
    "工程コード" VARCHAR(10) NOT NULL,
    "部門コード" VARCHAR(10) NOT NULL,
    "担当者コード" VARCHAR(10) NOT NULL,
    "作業日" DATE NOT NULL,
    "工数" DECIMAL(10, 2) NOT NULL,
    "備考" TEXT,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "作成者" VARCHAR(50),
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新者" VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_工数実績_作業指示番号 ON "工数実績データ"("作業指示番号");
CREATE INDEX IF NOT EXISTS idx_工数実績_工程コード ON "工数実績データ"("工程コード");
CREATE INDEX IF NOT EXISTS idx_工数実績_担当者コード ON "工数実績データ"("担当者コード");
CREATE INDEX IF NOT EXISTS idx_工数実績_作業日 ON "工数実績データ"("作業日");

-- 外部キー（H2の制約対応）
ALTER TABLE "工数実績データ" ADD CONSTRAINT IF NOT EXISTS fk_工数実績_作業指示
    FOREIGN KEY ("作業指示番号") REFERENCES "作業指示データ"("作業指示番号");
ALTER TABLE "工数実績データ" ADD CONSTRAINT IF NOT EXISTS fk_工数実績_工程
    FOREIGN KEY ("工程コード") REFERENCES "工程マスタ"("工程コード");
ALTER TABLE "工数実績データ" ADD CONSTRAINT IF NOT EXISTS fk_工数実績_部門
    FOREIGN KEY ("部門コード") REFERENCES "部門マスタ"("部門コード");
