-- ==================================================
-- 生産管理システム（PMS）デモ用スキーマ
-- H2 Database 互換（chapter23.md 準拠）
-- ==================================================

-- --------------------------------------------------
-- 単位マスタ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "単位マスタ" (
    "単位コード" VARCHAR(10) PRIMARY KEY,
    "単位記号" VARCHAR(10) NOT NULL,
    "単位名" VARCHAR(50) NOT NULL,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- --------------------------------------------------
-- 品目マスタ（世代管理対応）
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "品目マスタ" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "品目コード" VARCHAR(20) NOT NULL,
    "適用開始日" DATE NOT NULL,
    "適用停止日" DATE,
    "品名" VARCHAR(100) NOT NULL,
    "品目区分" VARCHAR(20) NOT NULL,
    "単位コード" VARCHAR(10),
    "リードタイム" INTEGER DEFAULT 0,
    "安全リードタイム" INTEGER DEFAULT 0,
    "安全在庫数" DECIMAL(15, 2) DEFAULT 0,
    "歩留率" DECIMAL(5, 2) DEFAULT 100,
    "最小ロット数" DECIMAL(15, 2) DEFAULT 1,
    "刻みロット数" DECIMAL(15, 2) DEFAULT 1,
    "最大ロット数" DECIMAL(15, 2),
    "有効期間" INTEGER,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_品目マスタ UNIQUE("品目コード", "適用開始日")
);

CREATE INDEX IF NOT EXISTS idx_品目マスタ_品目コード ON "品目マスタ"("品目コード");
CREATE INDEX IF NOT EXISTS idx_品目マスタ_品目区分 ON "品目マスタ"("品目区分");

-- --------------------------------------------------
-- 部品構成表（BOM）
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "部品構成表" (
    "親品目コード" VARCHAR(20) NOT NULL,
    "子品目コード" VARCHAR(20) NOT NULL,
    "適用開始日" DATE NOT NULL,
    "適用停止日" DATE,
    "基準数量" DECIMAL(15, 2) NOT NULL DEFAULT 1,
    "必要数量" DECIMAL(15, 2) NOT NULL,
    "不良率" DECIMAL(5, 2) DEFAULT 0,
    "工順" INTEGER,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("親品目コード", "子品目コード", "適用開始日")
);

CREATE INDEX IF NOT EXISTS idx_bom_親品目コード ON "部品構成表"("親品目コード");
CREATE INDEX IF NOT EXISTS idx_bom_子品目コード ON "部品構成表"("子品目コード");

-- --------------------------------------------------
-- カレンダマスタ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "カレンダマスタ" (
    "カレンダコード" VARCHAR(20) NOT NULL,
    "日付" DATE NOT NULL,
    "日付区分" VARCHAR(20) NOT NULL DEFAULT '稼働日',
    "稼働時間" DECIMAL(5, 2),
    "備考" VARCHAR(200),
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("カレンダコード", "日付")
);

-- --------------------------------------------------
-- 場所マスタ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "場所マスタ" (
    "場所コード" VARCHAR(20) PRIMARY KEY,
    "場所名" VARCHAR(100) NOT NULL,
    "場所区分" VARCHAR(20) NOT NULL,
    "親場所コード" VARCHAR(20),
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_場所マスタ_場所区分 ON "場所マスタ"("場所区分");

-- 自己参照外部キーは後で追加（H2の制約対応）
ALTER TABLE "場所マスタ" ADD CONSTRAINT IF NOT EXISTS fk_場所マスタ_親
    FOREIGN KEY ("親場所コード") REFERENCES "場所マスタ"("場所コード");

-- --------------------------------------------------
-- 取引先マスタ（世代管理対応）
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "取引先マスタ" (
    "取引先コード" VARCHAR(20) NOT NULL,
    "適用開始日" DATE NOT NULL,
    "適用停止日" DATE,
    "取引先名" VARCHAR(100) NOT NULL,
    "取引先カナ" VARCHAR(100),
    "取引先区分" VARCHAR(20) NOT NULL,
    "郵便番号" VARCHAR(10),
    "住所" VARCHAR(200),
    "電話番号" VARCHAR(20),
    "FAX番号" VARCHAR(20),
    "担当者名" VARCHAR(50),
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("取引先コード", "適用開始日")
);

CREATE INDEX IF NOT EXISTS idx_取引先マスタ_取引先区分 ON "取引先マスタ"("取引先区分");

-- --------------------------------------------------
-- 部門マスタ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "部門マスタ" (
    "部門コード" VARCHAR(10) PRIMARY KEY,
    "部門名" VARCHAR(100) NOT NULL,
    "部門パス" VARCHAR(500),
    "最下層区分" BOOLEAN DEFAULT FALSE,
    "有効開始日" DATE NOT NULL,
    "有効終了日" DATE,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- --------------------------------------------------
-- 担当者マスタ（世代管理対応）
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "担当者マスタ" (
    "担当者コード" VARCHAR(10) NOT NULL,
    "適用開始日" DATE NOT NULL,
    "適用停止日" DATE,
    "担当者名" VARCHAR(100) NOT NULL,
    "部門コード" VARCHAR(10),
    "メールアドレス" VARCHAR(255),
    "電話番号" VARCHAR(20),
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("担当者コード", "適用開始日")
);

-- --------------------------------------------------
-- 工程マスタ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "工程マスタ" (
    "工程コード" VARCHAR(10) PRIMARY KEY,
    "工程名" VARCHAR(100) NOT NULL,
    "工程区分" VARCHAR(20),
    "場所コード" VARCHAR(20),
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- --------------------------------------------------
-- 工程表
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "工程表" (
    "品目コード" VARCHAR(20) NOT NULL,
    "工順" INTEGER NOT NULL,
    "工程コード" VARCHAR(10) NOT NULL,
    "標準作業時間" DECIMAL(10, 2),
    "段取時間" DECIMAL(10, 2),
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("品目コード", "工順")
);

CREATE INDEX IF NOT EXISTS idx_工程表_品目コード ON "工程表"("品目コード");

-- --------------------------------------------------
-- 単価マスタ（世代管理対応）
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "単価マスタ" (
    "品目コード" VARCHAR(20) NOT NULL,
    "取引先コード" VARCHAR(20) NOT NULL,
    "適用開始日" DATE NOT NULL,
    "適用停止日" DATE,
    "単価" DECIMAL(15, 2) NOT NULL,
    "通貨コード" VARCHAR(3) DEFAULT 'JPY',
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("品目コード", "取引先コード", "適用開始日")
);

CREATE INDEX IF NOT EXISTS idx_単価マスタ_品目コード ON "単価マスタ"("品目コード");
CREATE INDEX IF NOT EXISTS idx_単価マスタ_取引先コード ON "単価マスタ"("取引先コード");

-- --------------------------------------------------
-- 欠点マスタ
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "欠点マスタ" (
    "欠点コード" VARCHAR(10) PRIMARY KEY,
    "欠点名" VARCHAR(100) NOT NULL,
    "欠点区分" VARCHAR(20),
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==================================================
-- 生産計画テーブル（chapter24.md 準拠）
-- ==================================================

-- --------------------------------------------------
-- 基準生産計画
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "基準生産計画" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MPS番号" VARCHAR(20) UNIQUE NOT NULL,
    "計画日" DATE NOT NULL,
    "品目コード" VARCHAR(20) NOT NULL,
    "計画数量" DECIMAL(15, 2) NOT NULL,
    "納期" DATE NOT NULL,
    "ステータス" VARCHAR(20) DEFAULT '草案' NOT NULL,
    "場所コード" VARCHAR(20),
    "備考" TEXT,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "作成者" VARCHAR(50),
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新者" VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_基準生産計画_品目コード ON "基準生産計画"("品目コード");
CREATE INDEX IF NOT EXISTS idx_基準生産計画_納期 ON "基準生産計画"("納期");
CREATE INDEX IF NOT EXISTS idx_基準生産計画_ステータス ON "基準生産計画"("ステータス");

-- --------------------------------------------------
-- オーダ情報（購買・製造共通）
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "オーダ情報" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "オーダNO" VARCHAR(20) UNIQUE NOT NULL,
    "オーダ種別" VARCHAR(20) NOT NULL,
    "品目コード" VARCHAR(20) NOT NULL,
    "着手予定日" DATE NOT NULL,
    "納期" DATE NOT NULL,
    "有効期限" DATE,
    "計画数量" DECIMAL(15, 2) NOT NULL,
    "場所コード" VARCHAR(20) NOT NULL,
    "ステータス" VARCHAR(20) DEFAULT '草案' NOT NULL,
    "MPS_ID" INTEGER,
    "親オーダID" INTEGER,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "作成者" VARCHAR(50),
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新者" VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_オーダ情報_品目コード ON "オーダ情報"("品目コード");
CREATE INDEX IF NOT EXISTS idx_オーダ情報_納期 ON "オーダ情報"("納期");
CREATE INDEX IF NOT EXISTS idx_オーダ情報_MPS_ID ON "オーダ情報"("MPS_ID");
CREATE INDEX IF NOT EXISTS idx_オーダ情報_オーダ種別 ON "オーダ情報"("オーダ種別");

-- 外部キー（H2の制約対応）
ALTER TABLE "オーダ情報" ADD CONSTRAINT IF NOT EXISTS fk_オーダ情報_MPS
    FOREIGN KEY ("MPS_ID") REFERENCES "基準生産計画"("ID");
ALTER TABLE "オーダ情報" ADD CONSTRAINT IF NOT EXISTS fk_オーダ情報_親オーダ
    FOREIGN KEY ("親オーダID") REFERENCES "オーダ情報"("ID");

-- --------------------------------------------------
-- 所要情報
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "所要情報" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "所要NO" VARCHAR(20) UNIQUE NOT NULL,
    "オーダID" INTEGER NOT NULL,
    "品目コード" VARCHAR(20) NOT NULL,
    "納期" DATE NOT NULL,
    "必要数量" DECIMAL(15, 2) NOT NULL,
    "引当済数量" DECIMAL(15, 2) DEFAULT 0 NOT NULL,
    "不足数量" DECIMAL(15, 2) DEFAULT 0 NOT NULL,
    "場所コード" VARCHAR(20) NOT NULL,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_所要情報_オーダID ON "所要情報"("オーダID");
CREATE INDEX IF NOT EXISTS idx_所要情報_品目コード ON "所要情報"("品目コード");

-- 外部キー（H2の制約対応）
ALTER TABLE "所要情報" ADD CONSTRAINT IF NOT EXISTS fk_所要情報_オーダ
    FOREIGN KEY ("オーダID") REFERENCES "オーダ情報"("ID");

-- --------------------------------------------------
-- 引当情報
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "引当情報" (
    "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "所要ID" INTEGER NOT NULL,
    "引当区分" VARCHAR(20) NOT NULL,
    "オーダID" INTEGER,
    "引当日" DATE NOT NULL,
    "引当数量" DECIMAL(15, 2) NOT NULL,
    "場所コード" VARCHAR(20) NOT NULL,
    "作成日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "更新日時" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_引当情報_所要ID ON "引当情報"("所要ID");

-- 外部キー（H2の制約対応）
ALTER TABLE "引当情報" ADD CONSTRAINT IF NOT EXISTS fk_引当情報_所要
    FOREIGN KEY ("所要ID") REFERENCES "所要情報"("ID");
ALTER TABLE "引当情報" ADD CONSTRAINT IF NOT EXISTS fk_引当情報_オーダ
    FOREIGN KEY ("オーダID") REFERENCES "オーダ情報"("ID");
